version: "3.3"
services:
  trevisan:
    hostname: "trevisan"
    build: .
    image: "trevisan"
    ports:
      - "5553:5553"
    volumes:
      - ./python:/app
    stdin_open: true
    tty: true
    shm_size: 2048m
    command: ["python3", "/app/extractor_server.py"]
    restart: unless-stopped

  verify:
    build:
      context: verifier
      dockerfile: Dockerfile
    image: "curby-verifier"
    command: ["100"]
    restart: no
    # volumes:
    #   - ./verifier/index.ts:/usr/src/app/index.ts
    depends_on:
      - trevisan
    profiles:
      - "verify"

networks:
  default:
    name: trevisan-network
