version: "3.3"
services:
  trevisan:
    hostname: "trevisan"
    build: .
    image: "trevisan"
    ports:
      - "5553:5553"
    volumes:
      - ./python:/app
    stdin_open: true
    tty: true
    shm_size: 2048m
    command: ["python3", "extractor_server.py"]
    restart: unless-stopped

networks:
  default:
    name: trevisan-network
