name: Test

on:
  workflow_run:
    workflows: [Docker]
    types:
      - completed

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context.payload.workflow_run, null, 2))
            
