name: Test

on:
  workflow_run:
    workflows: [Docker]
    types:
      - completed

jobs:
  echo:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Echo
        uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(github.event.workflow_run, null, 2))
            
